baseURL = "https://blog.zhoujie218.top/"
languageCode = "zh-CN"
defaultContentLanguage = "zh-hans"
title = "周杰个人博客"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X/G-XXXXXXXXXX

# Enable JSON output for search index
[outputs]
  home = ["HTML", "RSS", "JSON"]

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

## disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "zhoujie"
  
[params]
  author = "zhoujie"
  subtitle = "记录生活点滴"
  keywords = "zhoujie218,zhoujie218.top,zhou,blog.zhoujie218.top,周杰,记录点滴生活"
  description = "zhoujie218,zhoujie218.top,zhou,blog.zhoujie218.top,周杰,记录点滴生活"
  busuanzi = false #启用不算子网页统计
  googleAd = "ca-pub-6941806026814791"
  localSearch = false # 关闭本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  #customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  #customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录
  fancybox = true ##点击图片变大
  beian = "赣ICP备15001246号-2"
  # cdnJsSite = "cdn.bootcdn.net" # 默认：cdnjs.cloudflare.com



## 友情链接，可以多个

[[params.links]]
  title = "周杰的博客"
  name = "周杰的博客"
  url = "https://www.zhoujie218.top/"



## 侧边栏广告位
##[[params.ads]]
##  title = "【2022双11】ALL IN CLoud 低至1折"
##  url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=38xk7t2q"
##  img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"


## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = false
  repo = "your github repo" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"
## 配置 waline 评论系统,教程参考 https://waline.js.org/
[params.waline]
  enable = false
  placeholder = "欢迎来到我的小博客，如果对此文有什么想法请在这里告诉我！温馨提示，网络并非法外之地，请谨言慎行！"
  serverURL = "https://waline-492r55y75-vbskycn.vercel.app/" #换成你的serverURL

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"



## 配置网站菜单
[menu]

  [[menu.main]]
    identifier = "diannaowangruo"
    name = "电脑网络"
    url = "/categories/diannaowangruo/"
    weight = 2

  [[menu.main]]
    identifier = "wangyesheji"
    name = "网站设计"
    url = "/categories/wangyesheji/"
    weight = 3      
 
  [[menu.main]]
    identifier = "shenhuarizhi"
    name = "生活日志"
    url = "/categories/shenhuarizhi/"
    weight = 4
 
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 6

ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
